### ISSUE TITLE
Error on certStorage.remove

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/pvpkcs11#21]
```
Action: crypto/certificateStorage/removeItem
Error: C_DestroyObject
Exception: Error on SecItemDelete
    at Destroy (../../src/osx/certificate.cpp:238)
    at Destroy (../../src/osx/certificate.cpp:243)
    at DestroyObject (../../src/core/module.cpp:960)

Error for action: crypto/certificateStorage/removeItem
Error: CKR_FUNCTION_FAILED:6
    at Error (native) C_DestroyObject:504
    at X509Certificate.SessionObject.destroy (/Users/rmh/Downloads/electron-app/node_modules/graphene-pk11/build/object.js:47:18)
    at Pkcs11CertificateStorage.<anonymous> (/Users/rmh/Downloads/electron-app/node_modules/node-webcrypto-p11/built/cert_storage.js:95:35)
    at step (/Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:122:27)
    at Object.next (/Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:103:57)
    at /Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:96:75
    at Object.__awaiter (/Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:92:16)
    at Pkcs11CertificateStorage.removeItem (/Users/rmh/Downloads/electron-app/node_modules/node-webcrypto-p11/built/cert_storage.js:90:24)
    at LocalServer.<anonymous> (/Users/rmh/Downloads/electron-app/node_modules/webcrypto-local/out/local/server.js:570:68)
    at step (/Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:122:27)
    at Object.next (/Users/rmh/Downloads/electron-app/node_modules/tslib/tslib.js:103:57)
```

**Comment by microshine** [comment]
Added Error code to exception
